FROM neomediatech/ubuntu-base:24.04

ENV QT_GRAPHICSSYSTEM="native" \
    DISPLAY=":0"

COPY entrypoint.sh /
RUN chmod +x entrypoint.sh

SHELL ["/bin/bash", "-c"]

RUN ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

RUN apt-get update && \
    apt-get -y --no-install-recommends --no-install-suggests install \
            bzip2 wget ffmpeg libpulse0 apulse ca-certificates libgtk-3-bin && \
    apt-get -y --no-install-recommends --no-install-suggests dist-upgrade && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN echo "Downloading ..." && \
    wget -q -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" && \
    echo "Unpacking ..." && \
    tar xfj firefox.tar.bz2 && \
    ln -s /opt/firefox/firefox /usr/bin/ && \
    rm -f firefox.tar.bz2

CMD ["/bin/sh", "/entrypoint.sh"]
