#!/bin/sh

gw="$(hostname -i|awk -F. '{print $1"."$2"."$3".1"}')"

PREF_DIR="/usr/lib/firefox/browser/defaults/preferences"
mkdir -p $PREF_DIR
echo 'user_pref("network.proxy.socks", "'"$gw"'");' > $PREF_DIR/all-custom.js
echo 'user_pref("network.proxy.socks_port", 3333);' >> $PREF_DIR/all-custom.js
echo 'user_pref("network.proxy.socks_remote_dns", true);' >> $PREF_DIR/all-custom.js
echo 'user_pref("network.proxy.type", 1);' >> $PREF_DIR/all-custom.js
echo 'user_pref("network.trr.mode", 2);' >> $PREF_DIR/all-custom.js
echo 'pref("network.proxy.socks", "'"$gw"'");' >> $PREF_DIR/all-custom.js
echo 'pref("network.proxy.socks_port", 3333);' >> $PREF_DIR/all-custom.js
echo 'pref("network.proxy.socks_remote_dns", true);' >> $PREF_DIR/all-custom.js
echo 'pref("network.proxy.type", 1);' >> $PREF_DIR/all-custom.js
echo 'pref("network.trr.mode", 2);' >> $PREF_DIR/all-custom.js

userdel -f -r ubuntu 2>/dev/null

USER=firefox
USERID=1000
echo "creating new $USER with UID $USERID"
useradd -m $USER -u $USERID 
chown -R $USER /home/$USER
gpasswd -a $USER audio
cd /home/$USER 
PROFILE_NAME="custom"
su $USER -c "mkdir -p /home/firefox/.mozilla/firefox/$PROFILE_NAME"
su $USER -c "touch /home/firefox/.mozilla/firefox/profiles.ini"
echo "[Profile0]" > /home/firefox/.mozilla/firefox/profiles.ini
echo "Name=$PROFILE_NAME" >> /home/firefox/.mozilla/firefox/profiles.ini
echo "IsRelative=1" >> /home/firefox/.mozilla/firefox/profiles.ini
echo "Path=$PROFILE_NAME" >> /home/firefox/.mozilla/firefox/profiles.ini
echo "Default=1" >> /home/firefox/.mozilla/firefox/profiles.ini

cat <<EOF > /home/firefox/.mozilla/firefox/$PROFILE_NAME/prefs.js
// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.
user_pref("app.normandy.first_run", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("extensions.pendingOperations", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("network.proxy.socks", "$gw");
user_pref("network.proxy.socks_port", 3333);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.proxy.type", 1);
user_pref("network.trr.mode", 2);
user_pref("toolkit.startup.last_success", $(date +%s));
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
EOF
su $USER -c "apulse firefox -P 'custom' --private-window"
